import type { LucideIcon } from 'lucide-react';
import {
  LayoutGrid,
  MessageSquare,
  Workflow,
  BookOpen,
  Wrench,
  Map,
  BarChart3,
  Shield,
  Activity,
  Settings,
  Search,
  Bell,
  Sun,
  Moon,
  Menu,
  Sparkles,
  Zap,
  Users,
  Bot,
  Home,
  Landmark,
  GraduationCap,
  TrendingUp,
  Gavel,
  PiggyBank,
  TrainFront,
  ScrollText,
  BrainCircuit,
  Globe,
  Play,
  Heart,
  BedDouble,
  Bath,
  Maximize,
  ArrowUpRight,
  ArrowDownRight,
  FileText,
  CheckCircle2,
  AlertTriangle,
  Plus,
  ChevronDown,
  Send,
  Image as ImageIcon,
  Mic,
  Database,
  CreditCard,
  Mail,
  Calendar,
  Cloud,
  CircleDot,
  ScanSearch,
  Eye,
  Upload,
  Download,
  Copy,
  RefreshCw,
  Tag,
  AlignLeft,
  Boxes,
  Trash2,
  Clock,
  X,
  FilePlus2,
  Layers,
  FolderOpen,
  MessageCircle,
  ChevronRight,
  CheckCircle,
  Loader2,
  FileCode2,
  Table2,
  Presentation,
} from 'lucide-react';

/* ============================================================
   Maps the prototype's short icon names onto Lucide components,
   so every page references icons by a stable key.
   ============================================================ */
export const ICONS: Record<string, LucideIcon> = {
  grid: LayoutGrid,
  chat: MessageSquare,
  workflow: Workflow,
  book: BookOpen,
  tool: Wrench,
  map: Map,
  chart: BarChart3,
  shield: Shield,
  activity: Activity,
  settings: Settings,
  search: Search,
  bell: Bell,
  sun: Sun,
  moon: Moon,
  menu: Menu,
  sparkle: Sparkles,
  bolt: Zap,

  users: Users,
  bot: Bot,
  msg: MessageSquare,
  home: Home,
  bank: Landmark,
  school: GraduationCap,
  trend: TrendingUp,
  gavel: Gavel,
  invest: PiggyBank,
  train: TrainFront,
  policy: ScrollText,
  brain: BrainCircuit,
  globe: Globe,
  play: Play,
  heart: Heart,
  bed: BedDouble,
  bath: Bath,
  area: Maximize,
  arrowUp: ArrowUpRight,
  arrowDown: ArrowDownRight,
  doc: FileText,
  check: CheckCircle2,
  warn: AlertTriangle,
  plus: Plus,
  chevron: ChevronDown,
  send: Send,
  image: ImageIcon,
  mic: Mic,
  db: Database,
  card: CreditCard,
  mail: Mail,
  calendar: Calendar,
  cloud: Cloud,
  dot: CircleDot,
  vision: ScanSearch,
  eye: Eye,
  upload: Upload,
  download: Download,
  copy: Copy,
  refresh: RefreshCw,
  tag: Tag,
  text: AlignLeft,
  boxes: Boxes,
  trash: Trash2,
  clock: Clock,
  close: X,
  file: FileText,
  'file-add': FilePlus2,
  layers: Layers,
  folder: FolderOpen,
  'msg-circle': MessageCircle,
  'chevron-right': ChevronRight,
  'check-circle': CheckCircle,
  loader: Loader2,
  'file-code': FileCode2,
  table: Table2,
  slides: Presentation,
};

export function getIcon(name: string): LucideIcon {
  return ICONS[name] ?? CircleDot;
}
