"""Tests for EmbeddingService.

The BGE model is loaded once (module scope) and injected directly into the
class variable so all async tests reuse it without repeated 70s disk loads.
No mocks — every embedding is generated by the real model.
"""

import math
import time

import pytest
from sentence_transformers import SentenceTransformer

from app.services.embedding_service import EmbeddingService, _vec_literal

MODEL_NAME = EmbeddingService.MODEL_NAME
DIM = EmbeddingService.EMBEDDING_DIM


# ── Fixtures ──────────────────────────────────────────────────────────────────


@pytest.fixture(scope="module")
def bge_model() -> SentenceTransformer:
    """Load BGE model once for this test module and inject into service.

    Clears the reference on teardown so downstream test modules don't inherit
    the ~1.3 GB model allocation.
    """
    import gc

    model = SentenceTransformer(MODEL_NAME)
    EmbeddingService._model = model
    yield model
    EmbeddingService._model = None
    del model
    gc.collect()


# ── Helper ────────────────────────────────────────────────────────────────────


def cosine_similarity(a: list[float], b: list[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    mag_a = math.sqrt(sum(x * x for x in a))
    mag_b = math.sqrt(sum(y * y for y in b))
    if mag_a == 0 or mag_b == 0:
        return 0.0
    return dot / (mag_a * mag_b)


# ── Single embedding ──────────────────────────────────────────────────────────


class TestSingleEmbedding:
    async def test_dimension(self, bge_model):
        emb = await EmbeddingService.generate_embedding("测试文本")
        assert len(emb) == DIM

    async def test_returns_floats(self, bge_model):
        emb = await EmbeddingService.generate_embedding("real estate market")
        assert all(isinstance(v, float) for v in emb)

    async def test_normalized_unit_vector(self, bge_model):
        emb = await EmbeddingService.generate_embedding("北京房地产市场报告")
        magnitude = math.sqrt(sum(v * v for v in emb))
        assert abs(magnitude - 1.0) < 1e-4, f"Magnitude was {magnitude}"

    async def test_deterministic(self, bge_model):
        text = "北京市房地产市场分析"
        emb_a = await EmbeddingService.generate_embedding(text)
        emb_b = await EmbeddingService.generate_embedding(text)
        assert emb_a == emb_b

    async def test_chinese_text(self, bge_model):
        emb = await EmbeddingService.generate_embedding(
            "这是一份关于上海房地产市场的分析报告"
        )
        assert len(emb) == DIM
        assert all(isinstance(v, float) for v in emb)

    async def test_english_text(self, bge_model):
        emb = await EmbeddingService.generate_embedding(
            "Shanghai real estate market analysis report 2026"
        )
        assert len(emb) == DIM

    async def test_mixed_text(self, bge_model):
        emb = await EmbeddingService.generate_embedding(
            "北京 Beijing real estate 房地产 market analysis"
        )
        assert len(emb) == DIM


# ── Semantic similarity ────────────────────────────────────────────────────────


class TestSemanticSimilarity:
    async def test_similar_texts_have_high_similarity(self, bge_model):
        emb_a = await EmbeddingService.generate_embedding("北京房地产价格上涨")
        emb_b = await EmbeddingService.generate_embedding("北京房产市场价格升高")
        sim = cosine_similarity(emb_a, emb_b)
        assert sim > 0.80, f"Expected high similarity, got {sim:.4f}"

    async def test_unrelated_texts_have_low_similarity(self, bge_model):
        emb_a = await EmbeddingService.generate_embedding("北京房地产市场分析")
        emb_b = await EmbeddingService.generate_embedding("量子力学波粒二象性理论")
        sim = cosine_similarity(emb_a, emb_b)
        assert sim < 0.85, f"Unrelated texts were too similar: {sim:.4f}"

    async def test_identical_texts_have_similarity_one(self, bge_model):
        text = "上海浦东新区商业地产投资分析"
        emb_a = await EmbeddingService.generate_embedding(text)
        emb_b = await EmbeddingService.generate_embedding(text)
        sim = cosine_similarity(emb_a, emb_b)
        assert abs(sim - 1.0) < 1e-4, f"Expected 1.0, got {sim:.6f}"


# ── Batch embedding ───────────────────────────────────────────────────────────


class TestBatchEmbedding:
    async def test_batch_returns_correct_count(self, bge_model):
        texts = [f"这是第{i}个测试文本，用于批量嵌入测试。" for i in range(10)]
        results = await EmbeddingService.generate_embeddings(texts)
        assert len(results) == len(texts)

    async def test_batch_each_dim_correct(self, bge_model):
        texts = ["北京房地产", "上海市场分析", "深圳科技园区"]
        results = await EmbeddingService.generate_embeddings(texts)
        for emb in results:
            assert len(emb) == DIM

    async def test_batch_all_normalized(self, bge_model):
        texts = [f"文本{i} text {i}" for i in range(8)]
        results = await EmbeddingService.generate_embeddings(texts)
        for i, emb in enumerate(results):
            mag = math.sqrt(sum(v * v for v in emb))
            assert abs(mag - 1.0) < 1e-4, f"Chunk {i} magnitude={mag}"

    async def test_batch_consistent_with_single(self, bge_model):
        # Batch and single calls may differ by float epsilon (CPU batch
        # normalization); verify semantic equivalence via cosine ≈ 1.0
        texts = ["北京商业地产", "上海住宅市场"]
        batch = await EmbeddingService.generate_embeddings(texts)
        single_0 = await EmbeddingService.generate_embedding(texts[0])
        single_1 = await EmbeddingService.generate_embedding(texts[1])
        sim0 = cosine_similarity(batch[0], single_0)
        sim1 = cosine_similarity(batch[1], single_1)
        assert abs(sim0 - 1.0) < 1e-3, f"batch[0] vs single[0] sim={sim0:.6f}"
        assert abs(sim1 - 1.0) < 1e-3, f"batch[1] vs single[1] sim={sim1:.6f}"

    async def test_empty_list_returns_empty(self, bge_model):
        result = await EmbeddingService.generate_embeddings([])
        assert result == []

    async def test_batch_exceeding_batch_size(self, bge_model):
        # 40 texts > BATCH_SIZE=32 — exercises multi-batch path
        texts = [f"房地产市场分析第{i}部分，包含详细的价格走势和供需关系报告。" for i in range(40)]
        results = await EmbeddingService.generate_embeddings(texts)
        assert len(results) == 40
        for emb in results:
            assert len(emb) == DIM


# ── Performance ───────────────────────────────────────────────────────────────


class TestPerformance:
    async def test_batch_32_under_10_seconds(self, bge_model):
        texts = [
            f"第{i}块：北京市{i}区域房地产市场2026年度分析报告，包含价格指数和成交量数据。"
            for i in range(32)
        ]
        start = time.perf_counter()
        results = await EmbeddingService.generate_embeddings(texts)
        elapsed = time.perf_counter() - start
        assert len(results) == 32
        assert elapsed < 10.0, f"32 embeddings took {elapsed:.2f}s (limit: 10s)"

    async def test_throughput_not_degrade_on_repeat_calls(self, bge_model):
        texts = [f"市场数据{i}" for i in range(16)]
        t0 = time.perf_counter()
        await EmbeddingService.generate_embeddings(texts)
        first = time.perf_counter() - t0

        t1 = time.perf_counter()
        await EmbeddingService.generate_embeddings(texts)
        second = time.perf_counter() - t1

        # Second call should not be significantly slower than first
        assert second < first * 3.0 + 1.0, (
            f"Second call took {second:.2f}s vs first {first:.2f}s"
        )


# ── _vec_literal helper ───────────────────────────────────────────────────────


class TestVecLiteral:
    def test_format_starts_and_ends_with_brackets(self):
        s = _vec_literal([0.1, 0.2, 0.3])
        assert s.startswith("[")
        assert s.endswith("]")

    def test_correct_number_of_values(self):
        vals = [float(i) / 1000 for i in range(DIM)]
        s = _vec_literal(vals)
        inner = s[1:-1]
        parts = inner.split(",")
        assert len(parts) == DIM

    def test_eight_decimal_places(self):
        s = _vec_literal([1.0 / 3.0])
        inner = s[1:-1]  # remove brackets
        _, decimals = inner.split(".")
        assert len(decimals) == 8
